/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PProfileIdProfileImport } from './routes/p/$profileId/_profile'
import { Route as PProfileIdProfileIndexImport } from './routes/p/$profileId/_profile/index'
import { Route as PProfileIdProfileAccountsIndexImport } from './routes/p/$profileId/_profile/accounts/index'

// Create Virtual Routes

const PProfileIdImport = createFileRoute('/p/$profileId')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PProfileIdRoute = PProfileIdImport.update({
  id: '/p/$profileId',
  path: '/p/$profileId',
  getParentRoute: () => rootRoute,
} as any)

const PProfileIdProfileRoute = PProfileIdProfileImport.update({
  id: '/_profile',
  getParentRoute: () => PProfileIdRoute,
} as any)

const PProfileIdProfileIndexRoute = PProfileIdProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProfileIdProfileRoute,
} as any)

const PProfileIdProfileAccountsIndexRoute =
  PProfileIdProfileAccountsIndexImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => PProfileIdProfileRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/p/$profileId': {
      id: '/p/$profileId'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/p/$profileId/_profile': {
      id: '/p/$profileId/_profile'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdProfileImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/_profile/': {
      id: '/p/$profileId/_profile/'
      path: '/'
      fullPath: '/p/$profileId/'
      preLoaderRoute: typeof PProfileIdProfileIndexImport
      parentRoute: typeof PProfileIdProfileImport
    }
    '/p/$profileId/_profile/accounts/': {
      id: '/p/$profileId/_profile/accounts/'
      path: '/accounts'
      fullPath: '/p/$profileId/accounts'
      preLoaderRoute: typeof PProfileIdProfileAccountsIndexImport
      parentRoute: typeof PProfileIdProfileImport
    }
  }
}

// Create and export the route tree

interface PProfileIdProfileRouteChildren {
  PProfileIdProfileIndexRoute: typeof PProfileIdProfileIndexRoute
  PProfileIdProfileAccountsIndexRoute: typeof PProfileIdProfileAccountsIndexRoute
}

const PProfileIdProfileRouteChildren: PProfileIdProfileRouteChildren = {
  PProfileIdProfileIndexRoute: PProfileIdProfileIndexRoute,
  PProfileIdProfileAccountsIndexRoute: PProfileIdProfileAccountsIndexRoute,
}

const PProfileIdProfileRouteWithChildren =
  PProfileIdProfileRoute._addFileChildren(PProfileIdProfileRouteChildren)

interface PProfileIdRouteChildren {
  PProfileIdProfileRoute: typeof PProfileIdProfileRouteWithChildren
}

const PProfileIdRouteChildren: PProfileIdRouteChildren = {
  PProfileIdProfileRoute: PProfileIdProfileRouteWithChildren,
}

const PProfileIdRouteWithChildren = PProfileIdRoute._addFileChildren(
  PProfileIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdProfileRouteWithChildren
  '/p/$profileId/': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/accounts': typeof PProfileIdProfileAccountsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/accounts': typeof PProfileIdProfileAccountsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/p/$profileId': typeof PProfileIdRouteWithChildren
  '/p/$profileId/_profile': typeof PProfileIdProfileRouteWithChildren
  '/p/$profileId/_profile/': typeof PProfileIdProfileIndexRoute
  '/p/$profileId/_profile/accounts/': typeof PProfileIdProfileAccountsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$profileId' | '/p/$profileId/' | '/p/$profileId/accounts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$profileId' | '/p/$profileId/accounts'
  id:
    | '__root__'
    | '/'
    | '/p/$profileId'
    | '/p/$profileId/_profile'
    | '/p/$profileId/_profile/'
    | '/p/$profileId/_profile/accounts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProfileIdRoute: typeof PProfileIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProfileIdRoute: PProfileIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/p/$profileId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/p/$profileId": {
      "filePath": "p/$profileId",
      "children": [
        "/p/$profileId/_profile"
      ]
    },
    "/p/$profileId/_profile": {
      "filePath": "p/$profileId/_profile.tsx",
      "parent": "/p/$profileId",
      "children": [
        "/p/$profileId/_profile/",
        "/p/$profileId/_profile/accounts/"
      ]
    },
    "/p/$profileId/_profile/": {
      "filePath": "p/$profileId/_profile/index.tsx",
      "parent": "/p/$profileId/_profile"
    },
    "/p/$profileId/_profile/accounts/": {
      "filePath": "p/$profileId/_profile/accounts/index.tsx",
      "parent": "/p/$profileId/_profile"
    }
  }
}
ROUTE_MANIFEST_END */
